services:
  app:
    build:
      context: .
    image: cr.anon.network/bsky-handle-checker:latest
    container_name: bluesky-checker
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - NODE_ENV=production
